### ISSUE TITLE
About Active weapon skills icons

### ISSUE THREAD

**Issue by Apellamen** [Reetus/ClassicAssist#11]
![1](https://user-images.githubusercontent.com/47136830/74217650-6abcb900-4ceb-11ea-815f-2b1948889417.png)
1- after i change a weapon, the icons don't refresh. I need to activate a 
![2](https://user-images.githubusercontent.com/47136830/74217653-6bede600-4ceb-11ea-8755-f9a3a9238174.png)
2- if i'm wrestler, if i active disarm or parablow, the icons disappear. If I activate something like Death Strike, its appear again.
![3](https://user-images.githubusercontent.com/47136830/74217654-6c867c80-4ceb-11ea-9010-1075868aabff.png)
3- Everytime i launch again the client, i have to fix the icons position. It doesn't remember the last location.

**Comment by Apellamen** [comment]
4- primary (disarm) and secondary (parablow) of wrestling are inverted. (if i activate the primary by script, it activate parablow instead disarm)

**Comment by Reetus** [comment]
Fixed in 475fb724c6e58699b261fbf454134b9a8e7823e2

Except...
> 3- Everytime i launch again the client, i have to fix the icons position. It doesn't remember the last location.

I can't reproduce this, it successully saves the position for me....

**Comment by Apellamen** [comment]
You already tried to place the icons in the same place of the screenshots i suppose. I have no idea why it happens. But, it still happens. 
If i'm the only person to have ti problem, never mind. :)
